spring.application.name=autodrive

spring.datasource.url=url_banco_de_dados
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=seu_user
spring.datasource.password=sua_senha

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080